[agent]
"mail.sustech.edu.cn" = { smtp = "smtp.exmail.qq.com", pop = "pop.exmail.qq.com" }
"gmail.com" = { smtp = "smtp.gmail.com", pop = "pop.gmail.com" }
"lamptales.com" = { smtp = "smtp.lamptales.com", pop = "pop.lamptales.com" }

[server]
"exmail.qq.com" = { smtp = 1025, pop = 3110 }
"gmail.com" = { smtp = 2025, pop = 2110 }
"lamptales.com" = { smtp = 3025, pop = 3026 }

[accounts."exmail.qq.com"]
"usr1@mail.sustech.edu.cn" = "pass1"
"usr2@mail.sustech.edu.cn" = "pass2"

[accounts."gmail.com"]
"usr@gmail.com" = "pass"

[accounts."lamptales.com"]
"usr@lamptales.com" = "pass"
